version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
    - "5672:5672" # rabbit amqp port
    - "15672:15672" # rabbitmq management port
    environment:
      - RABBITMQ_DEFAULT_USER=admin       # 기본사용자 이름
      - RABBITMQ_DEFAULT_PASS=admin123!@# # 기본사용자 비밀번호