spring:
  config:
    import:
      - classpath:application-db.yaml

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  application:
    name: admin-api

  jpa:
    open-in-view: false

token:
  secret:
    key: AdminSpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

server:
  port: 8081
